import {describe, expect, it} from 'vitest'
import golden from './cron.golden.json'
import {
  compressValues,
  cronFields,
  describeCron,
  expandSimpleField,
  nextRuns,
  parseCron,
  validateCron,
} from './cron'

function formatLocal(d: Date): string {
  const p = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`
}

// Must match the `from` baked into cron.golden.json (generated by the Go
// harness running the daemon's own robfig parser on this machine).
const FROM = new Date(2026, 8, 5, 12, 34, 56, 0)

describe('cron parity with robfig (golden fixture)', () => {
  for (const [expr, runs] of Object.entries(golden.valid) as Array<[string, string[] | null]>) {
    it(`computes the same next runs as robfig for "${expr}"`, () => {
      const got = nextRuns(expr, FROM, 5)
      expect(got?.map(formatLocal)).toEqual(runs ?? [])
    })
  }

  for (const expr of Object.keys(golden.invalid)) {
    it(`rejects "${expr}" like robfig`, () => {
      expect(validateCron(expr)).not.toBeNull()
    })
  }
})

describe('parseCron', () => {
  it('accepts the canonical builder shapes', () => {
    for (const expr of [
      '0 9 * * *',
      '0 9,17 * * *',
      '30 8,20 * * 1-5',
      '0 9 23-26 * *',
      '0 9 23-26 9 *',
      '0 9 1-5,20-22 * *',
      '@every 90m',
      '@daily',
      '0 0 9 23-26 * *',
    ]) {
      expect(parseCron(expr).ok, expr).toBe(true)
    }
  })

  it('rejects empty input', () => {
    expect(validateCron('')).toBe('empty spec string')
    expect(validateCron('   ')).toBe('empty spec string')
  })

  it('reports out-of-range values per field', () => {
    expect(validateCron('61 * * * *')).toContain('above maximum (59)')
    expect(validateCron('0 24 * * *')).toContain('above maximum (23)')
    expect(validateCron('0 9 32 * *')).toContain('above maximum (31)')
    expect(validateCron('0 9 * * 7')).toContain('above maximum (6)')
    expect(validateCron('0 13 * * *')).toBeNull()
  })

  it('rejects reversed ranges and bad steps', () => {
    expect(validateCron('5-3 * * * *')).toContain('beyond end of range')
    expect(validateCron('*/0 * * * *')).toContain('step of range')
    expect(validateCron('0 9 5-2 9 *')).toContain('beyond end of range')
  })

  it('accepts ? as a star synonym', () => {
    expect(validateCron('0 9 ? * *')).toBeNull()
    expect(validateCron('0 9 * * ?')).toBeNull()
  })

  it('accepts month and weekday names but only in their own fields', () => {
    expect(validateCron('0 9 1 SEP *')).toBeNull()
    expect(validateCron('0 9 15-20 SEP-OCT *')).toBeNull()
    expect(validateCron('0 12 * * MON')).toBeNull()
    expect(validateCron('0 9 1 * JAN')).not.toBeNull()
    expect(validateCron('0 9 1 sep *')).toBeNull()
  })

  it('accepts N/step semantics', () => {
    expect(validateCron('1/15 9 * * *')).toBeNull()
  })

  it('accepts TZ-qualified specs for validation but flags preview as unsupported', () => {
    expect(validateCron('TZ=Europe/Paris 0 9 * * *')).toBeNull()
    expect(validateCron('CRON_TZ=Europe/Paris 0 9 * * *')).toBeNull()
    expect(nextRuns('TZ=Europe/Paris 0 9 * * *', FROM, 5)).toBeNull()
    expect(validateCron('TZ=Not/AZone 0 9 * * *')).not.toBeNull()
    expect(validateCron('TZ=Europe/Paris')).not.toBeNull()
  })

  it('returns no runs for schedules that never fire', () => {
    expect(nextRuns('0 9 31 2 *', FROM, 5)).toEqual([])
  })
})

describe('describeCron', () => {
  it('describes interval descriptors', () => {
    expect(describeCron('@every 90m')).toBe('Every 1h 30m')
    expect(describeCron('@every 15m')).toBe('Every 15 minutes')
    expect(describeCron('@every 2h')).toBe('Every 2 hours')
    expect(describeCron('@every 45s')).toBe('Every 45 seconds')
  })

  it('describes fixed descriptors', () => {
    expect(describeCron('@daily')).toBe('Every day at 00:00')
    expect(describeCron('@hourly')).toBe('Every hour at :00')
  })

  it('describes step patterns', () => {
    expect(describeCron('*/15 * * * *')).toBe('Every 15 minutes')
    expect(describeCron('0 */6 * * *')).toBe('Every 6 hours at :00')
    expect(describeCron('0 * * * *')).toBe('Every hour at :00')
  })

  it('describes day-of-month ranges like the builder emits them', () => {
    expect(describeCron('0 9 23-26 * *')).toBe('At 09:00, on day 23\u201326')
    expect(describeCron('0 9 23-26 9 *')).toBe('At 09:00, on day 23\u201326, in Sep')
    expect(describeCron('0 9 1,15 * *')).toBe('At 09:00, on days 1, 15')
    expect(describeCron('0 9 1-5,20-22 * *')).toBe('At 09:00, on days 1\u20135, 20\u201322')
  })

  it('describes weekday selections', () => {
    expect(describeCron('0 9 * * 1-5')).toBe('At 09:00, on Mon\u2013Fri')
    expect(describeCron('0 9 * * 0,6')).toBe('At 09:00, on Sun, Sat')
    expect(describeCron('30 8,20 * * 1-5')).toBe('At 08:30, 20:30, on Mon\u2013Fri')
  })

  it('falls back to the raw text for invalid input', () => {
    expect(describeCron('garbage here')).toBe('garbage here')
  })
})

describe('compressValues / expandSimpleField', () => {
  it('compresses contiguous runs to ranges', () => {
    expect(compressValues([1, 2, 3], 1, 31)).toBe('1-3')
    expect(compressValues([23, 24, 25, 26], 1, 31)).toBe('23-26')
    expect(compressValues([1, 15], 1, 31)).toBe('1,15')
    expect(compressValues([1, 2, 3, 20, 21, 22], 1, 31)).toBe('1-3,20-22')
    expect(compressValues([1, 2, 3, 4, 5], 1, 5)).toBe('*')
    expect(compressValues([], 1, 31)).toBe('')
  })

  it('expands plain number/range/list fields and rejects builder-hostile syntax', () => {
    expect(expandSimpleField('23-26', 1, 31)).toEqual([23, 24, 25, 26])
    expect(expandSimpleField('1,15', 1, 31)).toEqual([1, 15])
    expect(expandSimpleField('1-3,20-22', 1, 31)).toEqual([1, 2, 3, 20, 21, 22])
    expect(expandSimpleField('*/2', 1, 31)).toBeNull()
    expect(expandSimpleField('JAN', 1, 12)).toBeNull()
    expect(expandSimpleField('32', 1, 31)).toBeNull()
    expect(expandSimpleField('*', 1, 31)).toBeNull()
    expect(expandSimpleField('5-2', 1, 31)).toBeNull()
  })
})

describe('cronFields', () => {
  it('splits 5-field expressions without a seconds column', () => {
    const fields = cronFields('0 9 23-26 * *')
    expect(fields?.hasSeconds).toBe(false)
    expect(fields?.labels.map((l) => `${l.name}=${l.value}`)).toEqual([
      'Min=0',
      'Hour=9',
      'Day=23-26',
      'Month=*',
      'Weekday=*',
    ])
  })

  it('splits 6-field expressions with seconds', () => {
    const fields = cronFields('0 0 9 23-26 * *')
    expect(fields?.hasSeconds).toBe(true)
    expect(fields?.labels[0]).toEqual({name: 'Sec', value: '0'})
  })

  it('returns null for descriptors and malformed input', () => {
    expect(cronFields('@daily')).toBeNull()
    expect(cronFields('* * *')).toBeNull()
    expect(cronFields('')).toBeNull()
  })
})
